Disable debugging and Allure CLI installation steps
Comment out debugging steps and Allure CLI installation.

diff --git a/.github/workflows/email-reports.yml b/.github/workflows/email-reports.yml
--- a/.github/workflows/email-reports.yml
+++ b/.github/workflows/email-reports.yml
@@ -22,31 +22,31 @@ jobs:
             path: allure-results
             # path: . 
 
-      - name: List Allure Results Files - did for debugging
-        run: |
-          echo "Contents of allure-results folder:"
-          ls -R allure-results
-          echo "Check if container.json exists:"
-          find allure-results -name container.json || echo "container.json not found"
+      # - name: List Allure Results Files - did for debugging
+      #   run: |
+      #     echo "Contents of allure-results folder:"
+      #     ls -R allure-results
+      #     echo "Check if container.json exists:"
+      #     find allure-results -name container.json || echo "container.json not found"
 
-      - name: Install Allure CLI
-        run: |
-          curl -o allure.tgz -L https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
-          tar -xzf allure.tgz
-          sudo mv allure-2.27.0 /opt/allure
-          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
+      # - name: Install Allure CLI
+      #   run: |
+      #     curl -o allure.tgz -L https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
+      #     tar -xzf allure.tgz
+      #     sudo mv allure-2.27.0 /opt/allure
+      #     sudo ln -s /opt/allure/bin/allure /usr/bin/allure
           
       - name: Generate Allure report
         run: allure generate allure-results -o allure-report --clean
 
-      - name: List Allure Report contents - did for debugging
-        run: ls -R allure-report
+      # - name: List Allure Report contents - did for debugging
+      #   run: ls -R allure-report
 
-      - name: Upload the generated Allure report folder
-        uses: actions/upload-artifact@v4
-        with:
-           name: allure-report
-           path: allure-report
+      # - name: Upload the generated Allure report folder
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #      name: allure-report
+      #      path: allure-report
 
       - name: Deploy Allure report to GitHub Pages
         uses: peaceiris/actions-gh-pages@v3
